; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Final Fantasy 3:
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1

music_data_final_fantasy_3:
	db 1
	dw @instruments
	dw @samples-4
; 00 : Song 2
	dw @song0ch0
	dw @song0ch1
	dw @song0ch2
	dw @song0ch3
	dw @song0ch4
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env1,@env2,@env4,@env0 ; 00 : Duty 2

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $00,$cf,$7f,$00,$02
@env2:
	db $c0,$7f,$00,$01
@env3:
	db $7f,$00,$00
@env4:
	db $c2,$7f,$00,$00

@samples:

@tempo_env_1_mid:
	db $03,$05,$80

@song0ch0:
@song0ch0loop:
	db $47, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $7c, $4e, $ff, $80, $0d, $81, $7b, $83, $7a, $83, $79, $83, $78, $87
@song0ref19:
	db $7c, $4e, $00, $0f, $81, $7b, $83, $7a, $83, $79, $83, $78, $85
@song0ref32:
	db $7c, $11
@song0ref34:
	db $81, $7b, $83
@song0ref37:
	db $7a, $83, $79, $83, $78, $83, $7c, $14, $81, $7b, $83, $7a, $83, $79, $83, $78, $85
@song0ref54:
	db $7c, $4e, $ff, $19, $81, $7b, $83, $7a, $83, $79, $83
@song0ref65:
	db $78, $83, $7c, $4e, $00, $1b
@song0ref71:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83
@song0ref80:
	db $7c, $1d
@song0ref82:
	db $81, $7b, $83
@song0ref85:
	db $7a, $83, $79, $83, $78, $83, $7c, $20
@song0ref93:
	db $81
@song0ref94:
	db $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $25
@song0ref104:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $01, $27, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e
	db $00, $29
@song0ref130:
	db $81, $7b, $83
@song0ref133:
	db $7a, $83, $79, $83, $78, $81, $7c, $2c
@song0ref141:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83
@song0ref150:
	db $7c, $31
@song0ref152:
	db $81, $7b, $83
@song0ref155:
	db $7a, $83, $79, $83, $78, $81, $7c, $33
@song0ref163:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $35
@song0ref174:
	db $81
@song0ref175:
	db $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $38, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $3d
	db $41, $0b
	dw @song0ref174
	db $7c, $35
	db $41, $0a
	dw @song0ref152
	db $78, $81, $7c, $31
@song0ref208:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $2c, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $29
@song0ref230:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e, $01, $27, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e
	db $00, $25
	db $41, $0a
	dw @song0ref82
	db $78, $81, $7c, $1d, $81, $48
@song0ref265:
	db $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $1b
@song0ref275:
	db $81, $7b, $83
@song0ref278:
	db $7a, $83, $79, $83, $78, $81, $7c, $4e, $ff, $19
@song0ref288:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e, $00, $14
@song0ref301:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $11
@song0ref312:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83
@song0ref321:
	db $7c, $0f, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $ff, $0a
@song0ref336:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83
@song0ref345:
	db $7c, $0c
@song0ref347:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $0d, $81, $7b, $83, $7a, $83, $79, $83, $78, $83
@song0ref367:
	db $7c, $4e, $00, $11
@song0ref371:
	db $81, $7b, $83, $7a, $83, $79, $83
@song0ref378:
	db $78, $81, $7c, $16, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $18
	db $41, $0a
	dw @song0ref275
	db $78, $81, $7c, $4e, $00, $1d
@song0ref402:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $22, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $24
	db $41, $0b
	dw @song0ref93
@song0ref427:
	db $7c, $29
@song0ref429:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $2e, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $30
	db $41, $0b
	dw @song0ref141
@song0ref454:
	db $7c, $35
@song0ref456:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e, $ff, $3a, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e
	db $00, $35
	db $41, $0b
	dw @song0ref141
	db $7c, $30
	db $41, $0b
	dw @song0ref429
	db $7c, $29, $81, $48
	db $41, $0a
	dw @song0ref94
	db $7c, $24
	db $41, $0b
	dw @song0ref402
	db $7c, $1d
	db $41, $0b
	dw @song0ref275
	db $7c, $4e, $00, $18
	db $41, $0b
	dw @song0ref371
	db $7c, $11, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $ff, $0d
	db $41, $11
	dw @song0ref336
	db $7c, $4e, $00, $0f
	db $41, $0b
	dw @song0ref301
	db $7c, $14
	db $41, $0b
	dw @song0ref275
	db $7c, $4e, $00, $1b, $81, $7b, $83, $7a, $83, $79, $83, $78, $81
	db $41, $0b
	dw @song0ref80
	db $78, $81, $7c, $25
	db $41, $0b
	dw @song0ref230
	db $7c, $4e, $00, $29
	db $41, $0b
	dw @song0ref208
	db $41, $19
	dw @song0ref150
	db $81, $48
	db $41, $0a
	dw @song0ref175
	db $7c, $35
	db $41, $0b
	dw @song0ref152
	db $7c, $31
	db $41, $0b
	dw @song0ref130
	db $7c, $29
	db $41, $0b
	dw @song0ref104
	db $7c, $4e, $00, $25, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $20
	db $41, $0a
	dw @song0ref71
	db $78, $81, $7c, $1b
@song0ref619:
	db $81, $7b, $83
@song0ref622:
	db $7a, $83, $79, $83, $78, $83, $7c, $4e, $ff, $19, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $00, $14, $81
	db $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $11, $81, $7b, $83, $7a, $83, $79, $83, $78, $81
	db $41, $25
	dw @song0ref321
	db $41, $0b
	dw @song0ref275
@song0ref671:
	db $7c, $4e, $00, $1d
@song0ref675:
	db $81, $7b, $83, $7a, $83, $79, $83
@song0ref682:
	db $78, $81, $7c, $22, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $24
@song0ref697:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $25, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $29, $81, $48
@song0ref721:
	db $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $2e, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $30, $81, $7b, $83
	db $7a, $83, $79, $83, $78, $81, $7c, $31
	db $41, $0b
	dw @song0ref163
@song0ref756:
	db $7c, $4e, $ff, $3a, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e, $00, $35
@song0ref773:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $31, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $30
	db $41, $0b
	dw @song0ref429
	db $7c, $29
	db $41, $0b
	dw @song0ref93
	db $7c, $24
	db $41, $0b
	dw @song0ref402
	db $7c, $1d
	db $41, $0b
	dw @song0ref619
	db $7c, $4e, $00, $18, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $16
	db $41, $0b
	dw @song0ref301
	db $7c, $4e, $ff, $0d
@song0ref835:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $0c, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $0a
	db $41, $0b
	dw @song0ref347
@song0ref860:
	db $7c, $4e, $00, $12
@song0ref864:
	db $81, $7b, $83, $7a, $83
@song0ref869:
	db $79, $83, $78, $81, $7c, $14, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $16
	db $41, $0a
	dw @song0ref275
	db $78, $81, $7c, $4e, $00, $1e, $81, $7b, $81, $48, $81
	db $41, $08
	dw @song0ref85
	db $78, $81, $7c, $22
	db $41, $0b
	dw @song0ref93
	db $7c, $2a
	db $41, $0b
	dw @song0ref208
	db $7c, $2e
	db $41, $0b
	dw @song0ref141
@song0ref920:
	db $7c, $36
@song0ref922:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83
@song0ref931:
	db $7c, $38
@song0ref933:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $ff, $3a, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e
	db $00, $38, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $36
	db $41, $0b
	dw @song0ref141
	db $7c, $2e
	db $41, $0b
	dw @song0ref208
	db $7c, $2a
	db $41, $0b
	dw @song0ref93
	db $7c, $22
@song0ref985:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $20, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $1e
	db $41, $0b
	dw @song0ref275
	db $7c, $4e, $00, $16
	db $41, $0b
	dw @song0ref864
	db $7c, $12, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $ff, $0d
	db $41, $0b
	dw @song0ref336
	db $7c, $4e, $00, $0f, $81, $7b, $81, $48, $81
	db $41, $08
	dw @song0ref37
	db $41, $08
	dw @song0ref378
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $1b
	db $41, $0a
	dw @song0ref82
	db $41, $0d
	dw @song0ref682
@song0ref1067:
	db $7c, $4e, $01, $27, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e, $00, $2c, $81
	db $41, $09
	dw @song0ref721
	db $78, $81, $7c, $30, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $33
	db $41, $0b
	dw @song0ref174
	db $7c, $4e, $ff, $3a, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $00, $3c
	db $41, $0b
	dw @song0ref456
@song0ref1126:
	db $7c, $4e, $00, $38
@song0ref1130:
	db $81, $7b, $83
@song0ref1133:
	db $7a, $83, $79, $83, $78, $83, $7c, $33, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $30
	db $41, $0b
	dw @song0ref429
	db $7c, $2c
	db $41, $0b
	dw @song0ref230
	db $7c, $4e, $00, $24
	db $41, $0b
	dw @song0ref402
	db $7c, $20, $81
	db $41, $0a
	dw @song0ref265
	db $7c, $18, $81, $7b, $81, $48, $81, $7a, $83, $79, $83, $78, $83, $7c, $16
	db $41, $0a
	dw @song0ref864
	db $78, $81, $7c, $0f, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $09
@song0ref1206:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $ff, $0d, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e
	db $00, $10
	db $41, $0b
	dw @song0ref864
@song0ref1235:
	db $7c, $4e, $ff, $15, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $19, $81, $7b, $83, $7a, $83, $79, $83, $78, $83
	db $7c, $4e, $00, $1c
	db $41, $0b
	dw @song0ref985
	db $7c, $21
	db $41, $0b
	dw @song0ref697
	db $7c, $28
	db $41, $0b
	dw @song0ref130
	db $7c, $2d
	db $41, $0a
	dw @song0ref773
	db $78, $83, $7c, $34
	db $41, $0b
	dw @song0ref174
	db $7c, $39
	db $41, $0a
	dw @song0ref174
	db $78, $81, $7c, $34
	db $41, $0b
	dw @song0ref141
	db $7c, $2d
	db $41, $0b
	dw @song0ref208
@song0ref1305:
	db $7c, $28, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $25, $81, $7b, $81, $48, $81, $7a, $83, $79, $83, $78, $81
	db $7c, $21
	db $41, $0a
	dw @song0ref82
	db $78, $81, $7c, $1c
	db $41, $0b
	dw @song0ref619
	db $7c, $15
	db $41, $0b
	dw @song0ref288
@song0ref1346:
	db $7c, $10
@song0ref1348:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e, $ff, $0d, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $0b
	db $81, $7b, $83
@song0ref1375:
	db $7a, $83, $79, $83, $78, $83, $7c, $4e, $00, $0f, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $12
@song0ref1396:
	db $81, $7b, $83, $7a, $83
@song0ref1401:
	db $79, $83, $78, $83, $7c, $16, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $ff, $17, $81, $7b, $83, $7a, $83
	db $79, $83, $78, $81, $7c, $4e, $00, $1b, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $1e
	db $41, $0b
	dw @song0ref675
	db $7c, $23
	db $41, $0b
	dw @song0ref104
	db $7c, $4e, $00, $2a, $81
	db $41, $0a
	dw @song0ref721
	db $7c, $2f
	db $41, $0b
	dw @song0ref152
	db $7c, $36
	db $41, $0b
	dw @song0ref933
	db $7c, $4e, $00, $3b
	db $41, $0b
	dw @song0ref933
	db $7c, $4e, $00, $36, $81, $7b, $81, $48, $81
	db $41, $09
	dw @song0ref1133
	db $7c, $2f
	db $41, $0a
	dw @song0ref429
	db $78, $83, $7c, $2a
	db $41, $0a
	dw @song0ref230
	db $78, $85, $7c, $4e, $00, $23
	db $41, $0a
	dw @song0ref402
@song0ref1510:
	db $78, $85, $7c, $1e, $81, $7b, $83, $7a, $83, $79, $83, $78, $85, $7c, $1b, $81, $7b, $83, $7a, $83, $79, $83, $78, $85
	db $7c, $4e, $ff, $17, $81, $7b, $83, $7a, $83, $79, $83, $78, $85, $7c, $4e, $00, $16, $81, $7b, $83, $7a, $83, $79, $83
	db $78, $87, $77, $81
@song0ref1562:
	db $7c, $12, $81, $7b, $83, $7a, $83, $79, $83, $78, $87, $7c, $0f, $81, $7b, $83, $7a, $83, $79, $83, $78, $87, $77, $81
	db $7c, $4e, $ff, $0d, $81, $7b, $83, $7a, $83, $79, $83, $78, $87, $77, $81
	db $41, $0b
	dw @song0ref19
	db $78, $85, $7c, $14
	db $41, $0a
	dw @song0ref619
	db $41, $21
	dw @song0ref65
	db $7b, $81, $48, $81
	db $41, $22
	dw @song0ref133
	db $41, $0b
	dw @song0ref174
	db $7c, $35
	db $41, $0b
	dw @song0ref152
	db $7c, $31
	db $41, $0b
	dw @song0ref130
	db $7c, $29
	db $41, $0a
	dw @song0ref104
	db $78, $81, $7c, $4e, $00, $25
	db $41, $0a
	dw @song0ref82
	db $78, $81, $7c, $1d, $81
	db $41, $41
	dw @song0ref265
	db $81, $7b, $81, $48, $81
	db $41, $09
	dw @song0ref278
	db $41, $17
	dw @song0ref671
	db $78, $81
	db $41, $0d
	dw @song0ref427
	db $41, $0b
	dw @song0ref141
	db $41, $0d
	dw @song0ref454
	db $41, $0b
	dw @song0ref141
	db $7c, $30
	db $41, $0b
	dw @song0ref429
	db $7c, $29
	db $41, $0b
	dw @song0ref93
	db $7c, $24
	db $41, $0b
	dw @song0ref402
	db $7c, $1d
	db $41, $0b
	dw @song0ref619
	db $7c, $4e, $00, $18
	db $41, $0b
	dw @song0ref1396
	db $7c, $11
	db $41, $0b
	dw @song0ref1206
	db $41, $09
	dw @song0ref345
	db $48
	db $41, $09
	dw @song0ref1375
	db $41, $0b
	dw @song0ref32
	db $78, $81
	db $41, $0b
	dw @song0ref54
	db $78, $81
	db $41, $0b
	dw @song0ref80
	db $78, $81, $7c, $25
	db $41, $0b
	dw @song0ref230
	db $7c, $4e, $00, $29
	db $41, $0b
	dw @song0ref208
	db $7c, $31
	db $41, $0b
	dw @song0ref1130
	db $7c, $35
	db $41, $0b
	dw @song0ref922
	db $7c, $3d
	db $41, $0b
	dw @song0ref174
	db $7c, $35
	db $41, $0b
	dw @song0ref152
	db $7c, $31
	db $41, $0b
	dw @song0ref130
	db $7c, $29
	db $41, $0b
	dw @song0ref104
	db $7c, $4e, $00, $25
	db $41, $0b
	dw @song0ref985
@song0ref1784:
	db $7c, $1d
@song0ref1786:
	db $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $1b, $81, $7b, $83, $48
	db $41, $15
	dw @song0ref622
	db $7c, $0f, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e, $ff, $0a
	db $41, $0b
	dw @song0ref835
	db $7c, $0d, $81, $7b, $83, $7a, $83, $79, $83, $78, $81
	db $41, $0d
	dw @song0ref367
	db $41, $0b
	dw @song0ref275
	db $41, $1a
	dw @song0ref671
	db $41, $11
	dw @song0ref721
	db $41, $0b
	dw @song0ref163
	db $41, $11
	dw @song0ref756
	db $78, $83, $7c, $30, $81
	db $41, $0a
	dw @song0ref721
	db $7c, $29
	db $41, $08
	dw @song0ref697
	db $48, $7a, $83, $79, $83, $78, $81, $7c, $24
	db $41, $0b
	dw @song0ref402
	db $7c, $1d
	db $41, $0b
	dw @song0ref619
	db $7c, $4e, $00, $18
	db $41, $0b
	dw @song0ref1396
	db $7c, $11
	db $41, $0b
	dw @song0ref1348
	db $7c, $0c, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $0a
	db $41, $0b
	dw @song0ref347
	db $41, $0d
	dw @song0ref860
	db $41, $0b
	dw @song0ref275
	db $7c, $4e, $00, $1e
	db $41, $0b
	dw @song0ref985
	db $7c, $22
	db $41, $0a
	dw @song0ref697
	db $78, $81, $7c, $2a
	db $41, $0b
	dw @song0ref208
	db $7c, $2e
	db $41, $0b
	dw @song0ref141
	db $41, $15
	dw @song0ref920
	db $48, $7a, $83, $79, $83, $78, $81, $7c, $36
	db $41, $0b
	dw @song0ref141
	db $7c, $2e
	db $41, $0b
	dw @song0ref208
	db $7c, $2a
	db $41, $0b
	dw @song0ref93
	db $7c, $22
	db $41, $0a
	dw @song0ref82
	db $78, $81, $7c, $1e
	db $41, $0b
	dw @song0ref619
	db $7c, $4e, $00, $16
	db $41, $0b
	dw @song0ref864
	db $7c, $12
	db $41, $0b
	dw @song0ref1206
	db $7c, $0c, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $00, $0f
	db $41, $0a
	dw @song0ref34
	db $41, $08
	dw @song0ref378
	db $41, $08
	dw @song0ref1786
	db $41, $08
	dw @song0ref85
	db $41, $0d
	dw @song0ref682
	db $41, $08
	dw @song0ref1067
	db $41, $0d
	dw @song0ref721
	db $48
	db $41, $09
	dw @song0ref155
	db $41, $0b
	dw @song0ref931
	db $78, $81, $7c, $4e, $00, $3c
	db $41, $0b
	dw @song0ref456
	db $41, $0d
	dw @song0ref1126
	db $41, $0b
	dw @song0ref429
	db $7c, $2c
	db $41, $0b
	dw @song0ref230
	db $7c, $4e, $00, $24
	db $41, $0b
	dw @song0ref402
	db $7c, $20, $81
	db $41, $0a
	dw @song0ref265
	db $7c, $18
	db $41, $0b
	dw @song0ref1396
	db $7c, $14
	db $41, $0b
	dw @song0ref312
	db $7c, $09
	db $41, $0b
	dw @song0ref1348
	db $7c, $4e, $00, $10
	db $41, $0b
	dw @song0ref864
	db $41, $0d
	dw @song0ref1235
	db $41, $08
	dw @song0ref985
	db $7a, $81, $48, $81, $79, $83, $78, $83, $7c, $21
	db $41, $0b
	dw @song0ref697
	db $7c, $28
	db $41, $0b
	dw @song0ref130
	db $7c, $2d
	db $41, $0a
	dw @song0ref773
	db $78, $83, $7c, $34
	db $41, $0b
	dw @song0ref174
	db $7c, $39
	db $41, $0b
	dw @song0ref174
	db $7c, $34
	db $41, $0a
	dw @song0ref773
	db $78, $83, $7c, $2d
	db $41, $0a
	dw @song0ref130
	db $78, $81
	db $41, $08
	dw @song0ref1305
	db $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $21
	db $41, $0a
	dw @song0ref82
	db $78, $81, $7c, $1c
	db $41, $0b
	dw @song0ref619
	db $7c, $15
	db $41, $0b
	dw @song0ref288
	db $41, $1b
	dw @song0ref1346
	db $7a, $81, $48, $81
	db $41, $0d
	dw @song0ref1401
@song0ref2179:
	db $78, $83, $7c, $4e, $00, $1b, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $1e
	db $41, $0b
	dw @song0ref402
	db $7c, $23
	db $41, $0b
	dw @song0ref104
	db $7c, $4e, $00, $2a, $81
	db $41, $0a
	dw @song0ref721
	db $7c, $2f
	db $41, $0b
	dw @song0ref152
	db $7c, $36
	db $41, $0b
	dw @song0ref933
	db $7c, $4e, $00, $3b
	db $41, $0b
	dw @song0ref933
	db $7c, $4e, $00, $36
	db $41, $0b
	dw @song0ref1130
	db $7c, $2f
	db $41, $0a
	dw @song0ref429
	db $78, $83, $7c, $2a, $81, $7b, $83, $7a, $83, $79, $83, $78, $85, $7c, $4e, $01, $27, $81, $7b, $83, $7a, $83, $79, $83
	db $78, $83, $7c, $4e, $00, $23
	db $41, $0a
	dw @song0ref402
	db $41, $11
	dw @song0ref1510
	db $48, $79, $83, $78, $87, $7c, $4e, $00, $16, $81, $7b, $83, $7a, $83, $79, $83, $78, $87
	db $41, $14
	dw @song0ref1562
	db $41, $0b
	dw @song0ref19
	db $78, $85, $7c, $14
	db $41, $0a
	dw @song0ref619
	db $41, $44
	dw @song0ref65
	db $41, $0b
	dw @song0ref174
	db $7c, $35
	db $41, $0b
	dw @song0ref152
	db $7c, $31
	db $41, $08
	dw @song0ref130
	db $7a, $81, $48, $81, $79, $83, $78, $83, $7c, $29
	db $41, $0a
	dw @song0ref104
	db $78, $81, $7c, $4e, $00, $25
	db $41, $0a
	dw @song0ref82
	db $78, $81, $7c, $1d, $81
	db $41, $41
	dw @song0ref265
	db $41, $0b
	dw @song0ref275
	db $41, $17
	dw @song0ref671
	db $78, $81
	db $41, $0d
	dw @song0ref427
	db $41, $0b
	dw @song0ref141
	db $41, $09
	dw @song0ref454
	db $7a, $81, $48, $81, $79, $83, $78, $81, $7c, $4e, $00, $35
	db $41, $0b
	dw @song0ref141
	db $7c, $30
	db $41, $0b
	dw @song0ref429
	db $7c, $29
	db $41, $0b
	dw @song0ref93
	db $7c, $24
	db $41, $0b
	dw @song0ref402
	db $7c, $1d
	db $41, $0b
	dw @song0ref619
	db $7c, $4e, $00, $18
	db $41, $0b
	dw @song0ref1396
	db $7c, $11
	db $41, $0b
	dw @song0ref1206
	db $41, $0c
	dw @song0ref345
	db $7c, $4e, $00, $0f
	db $41, $0b
	dw @song0ref301
	db $7c, $14
	db $41, $0b
	dw @song0ref275
	db $7c, $4e, $00, $1b, $81, $7b, $83, $7a, $83, $79, $83, $78, $81
	db $41, $0b
	dw @song0ref80
	db $78, $81, $7c, $25
	db $41, $0b
	dw @song0ref230
	db $7c, $4e, $00, $29
	db $41, $08
	dw @song0ref208
	db $7a, $81, $48, $81, $79, $83, $78, $81, $7c, $31
	db $41, $0b
	dw @song0ref1130
	db $7c, $35
	db $41, $0b
	dw @song0ref922
	db $7c, $3d
	db $41, $0b
	dw @song0ref174
	db $7c, $35
	db $41, $0b
	dw @song0ref152
	db $7c, $31
	db $41, $0b
	dw @song0ref130
	db $7c, $29
	db $41, $0b
	dw @song0ref104
	db $7c, $4e, $00, $25
	db $41, $0b
	dw @song0ref985
	db $41, $09
	dw @song0ref1784
	db $41, $15
	dw @song0ref622
	db $7c, $0f, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $4e, $ff, $0a
	db $41, $0b
	dw @song0ref835
	db $7c, $0d, $81, $7b, $83, $7a, $83, $79, $83, $78, $81
	db $41, $0d
	dw @song0ref367
	db $41, $09
	dw @song0ref275
	db $48, $79, $83, $78, $83
	db $41, $1a
	dw @song0ref671
	db $41, $11
	dw @song0ref721
	db $41, $0b
	dw @song0ref163
	db $41, $11
	dw @song0ref756
	db $78, $83, $7c, $30, $81
	db $41, $0a
	dw @song0ref721
	db $7c, $29
	db $41, $0a
	dw @song0ref697
	db $78, $81, $7c, $24
	db $41, $0b
	dw @song0ref402
	db $7c, $1d
	db $41, $0b
	dw @song0ref619
	db $7c, $4e, $00, $18
	db $41, $0b
	dw @song0ref1396
	db $7c, $11
	db $41, $0b
	dw @song0ref1348
	db $7c, $0c, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c, $0a
	db $41, $09
	dw @song0ref347
	db $48, $79, $83, $78, $83
	db $41, $0d
	dw @song0ref860
	db $41, $0b
	dw @song0ref275
	db $7c, $4e, $00, $1e
	db $41, $0b
	dw @song0ref985
	db $7c, $22
	db $41, $0a
	dw @song0ref697
	db $78, $81, $7c, $2a
	db $41, $0b
	dw @song0ref208
	db $7c, $2e
	db $41, $0b
	dw @song0ref141
	db $41, $19
	dw @song0ref920
	db $41, $0b
	dw @song0ref141
	db $7c, $2e
	db $41, $0b
	dw @song0ref208
	db $7c, $2a
	db $41, $0b
	dw @song0ref93
	db $7c, $22
	db $41, $0a
	dw @song0ref82
	db $78, $81, $7c, $1e
	db $41, $0b
	dw @song0ref619
	db $7c, $4e, $00, $16, $81, $7b, $83, $7a, $83, $48
	db $41, $08
	dw @song0ref869
	db $7c, $12
	db $41, $0b
	dw @song0ref1206
	db $7c, $0c, $81, $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $4e, $00, $0f
	db $41, $0a
	dw @song0ref34
	db $41, $08
	dw @song0ref378
	db $41, $08
	dw @song0ref1786
	db $41, $08
	dw @song0ref85
	db $41, $0d
	dw @song0ref682
	db $41, $08
	dw @song0ref1067
	db $41, $10
	dw @song0ref721
	db $7c, $33
	db $41, $10
	dw @song0ref922
	db $78, $81, $7c, $4e, $00, $3c
	db $41, $0b
	dw @song0ref456
	db $41, $0d
	dw @song0ref1126
	db $41, $0b
	dw @song0ref429
	db $7c, $2c
	db $41, $09
	dw @song0ref230
	db $48, $79, $83, $78, $81, $7c, $4e, $00, $24
	db $41, $0b
	dw @song0ref402
	db $7c, $20, $81
	db $41, $0a
	dw @song0ref265
	db $7c, $18
	db $41, $0b
	dw @song0ref1396
	db $7c, $14
	db $41, $0b
	dw @song0ref312
	db $7c, $09
	db $41, $0b
	dw @song0ref1348
	db $7c, $4e, $00, $10
	db $41, $0b
	dw @song0ref864
	db $41, $0d
	dw @song0ref1235
	db $41, $0b
	dw @song0ref985
	db $7c, $21
	db $41, $0b
	dw @song0ref697
	db $7c, $28
	db $41, $0b
	dw @song0ref130
	db $7c, $2d
	db $41, $0a
	dw @song0ref773
	db $78, $83, $7c, $34
	db $41, $0b
	dw @song0ref174
	db $7c, $39
	db $41, $0b
	dw @song0ref174
	db $7c, $34, $81, $7b, $83, $7a, $83, $48, $79, $83, $78, $81, $7c, $31, $81, $7b, $83, $7a, $83, $79, $83, $78, $83, $7c
	db $2d
	db $41, $0a
	dw @song0ref130
	db $78, $81
	db $41, $08
	dw @song0ref1305
	db $7b, $83, $7a, $83, $79, $83, $78, $81, $7c, $21
	db $41, $0a
	dw @song0ref82
	db $78, $81, $7c, $1c
	db $41, $0b
	dw @song0ref619
	db $7c, $15
	db $41, $0b
	dw @song0ref288
	db $41, $29
	dw @song0ref1346
	db $41, $08
	dw @song0ref2179
	db $41, $0b
	dw @song0ref402
	db $7c, $23
	db $41, $0b
	dw @song0ref104
	db $7c, $4e, $00, $2a, $81
	db $41, $0a
	dw @song0ref721
	db $7c, $2f
	db $41, $09
	dw @song0ref152
	db $79, $81, $48, $81, $78, $83, $7c, $36
	db $41, $0b
	dw @song0ref933
	db $7c, $4e, $00, $3b
	db $41, $0b
	dw @song0ref933
	db $7c, $4e, $00, $36, $ff, $ff, $ff, $ab, $42
	dw @song0ch0loop
@song0ch1:
@song0ch1loop:
	db $9d, $76, $4e, $fe, $80
@song0ref2954:
	db $0d, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $85, $76, $4e, $ff, $0f, $81, $75, $83, $4e, $00, $83, $74, $83
	db $4e, $ff, $85, $76, $11
@song0ref2983:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $14, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $85
	db $76, $4e, $fe, $19
@song0ref3011:
	db $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $81
@song0ref3022:
	db $76, $4e, $ff, $1b
@song0ref3026:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83
@song0ref3037:
	db $76, $1d
@song0ref3039:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $20
@song0ref3052:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $25
@song0ref3065:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $4e, $00, $27, $81, $75, $83, $4e, $01, $83, $74, $83
@song0ref3088:
	db $4e, $00, $81, $76, $4e, $ff, $29
@song0ref3095:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $2c
@song0ref3108:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $31
@song0ref3121:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $33, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81
	db $76, $35
@song0ref3147:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $38, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81
	db $76, $3d
	db $41, $0b
	dw @song0ref3147
	db $76, $35
	db $41, $0b
	dw @song0ref3121
	db $76, $31
	db $41, $0b
	dw @song0ref3095
	db $76, $29
	db $41, $0b
	dw @song0ref3065
	db $76, $4e, $ff, $25, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $20
	db $41, $0a
	dw @song0ref3026
	db $4e, $ff, $81, $76, $1b
@song0ref3216:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $4e, $fe, $19
@song0ref3231:
	db $81, $75, $83, $4e, $ff, $83, $74, $83
@song0ref3239:
	db $4e, $fe, $81, $76, $4e, $ff, $14
@song0ref3246:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $11
@song0ref3259:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $0f, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83
	db $76, $4e, $fe, $0a
@song0ref3287:
	db $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $81, $76, $0c
@song0ref3300:
	db $81, $75, $83
@song0ref3303:
	db $4e, $ff, $83, $74, $83, $4e, $fe, $83, $76, $0d, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $81, $76, $4e, $ff
	db $11
@song0ref3328:
	db $81, $75, $83, $4e, $00, $83, $74, $83
@song0ref3336:
	db $4e, $ff, $83, $76, $16, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $18
	db $41, $0b
	dw @song0ref3216
@song0ref3357:
	db $76, $4e, $ff, $1d
@song0ref3361:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $22
@song0ref3374:
	db $81, $75, $83, $4e, $00, $83, $74, $83
@song0ref3382:
	db $4e, $ff, $81, $76, $24
@song0ref3387:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83
@song0ref3398:
	db $76, $25
@song0ref3400:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $29
@song0ref3413:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $2e, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83
	db $76, $30
	db $41, $0b
	dw @song0ref3108
@song0ref3442:
	db $76, $35
@song0ref3444:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $4e, $fe, $3a, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e
	db $fe, $83, $76, $4e, $ff, $35
	db $41, $0b
	dw @song0ref3108
	db $76, $30
	db $41, $0b
	dw @song0ref3413
	db $76, $29
	db $41, $0b
	dw @song0ref3052
	db $76, $24, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $22
	db $41, $0a
	dw @song0ref3026
@song0ref3505:
	db $4e, $ff, $81, $76, $4e, $fe, $19, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $83, $76, $4e, $ff, $18, $81, $75
	db $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $16
	db $41, $0b
	dw @song0ref3246
	db $76, $4e, $fe, $0d
	db $41, $11
	dw @song0ref3287
	db $76, $4e, $ff, $0f
	db $41, $0b
	dw @song0ref3246
	db $76, $14
	db $41, $0b
	dw @song0ref3216
	db $41, $0b
	dw @song0ref3022
	db $4e, $ff, $81, $76, $20
	db $41, $0b
	dw @song0ref3387
@song0ref3573:
	db $76, $4e, $00, $27, $81, $75, $83, $4e, $01, $83, $74, $83, $4e, $00, $83, $76, $4e, $ff, $29
@song0ref3592:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $2c
@song0ref3605:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $31
@song0ref3618:
	db $81, $75, $83
@song0ref3621:
	db $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $33, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $35
@song0ref3644:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $38, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83
	db $76, $3d
	db $41, $0a
	dw @song0ref3644
	db $4e, $ff, $81, $76, $35
	db $41, $0b
	dw @song0ref3121
	db $76, $31
	db $41, $0b
	dw @song0ref3095
	db $76, $29
	db $41, $0b
	dw @song0ref3065
	db $76, $4e, $ff, $25
	db $41, $0b
	dw @song0ref3039
@song0ref3698:
	db $76, $1d
@song0ref3700:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $1b
@song0ref3713:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $4e, $fe, $19, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e
	db $fe, $83, $76, $4e, $ff, $14
@song0ref3743:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $11, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83
	db $76, $0f, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $4e, $fe, $0a
@song0ref3784:
	db $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $83
@song0ref3795:
	db $76, $0c, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $81, $76, $0d, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e
	db $fe, $83, $76, $4e, $ff, $11
@song0ref3825:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $16, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81
	db $76, $18
	db $41, $0b
	dw @song0ref3216
	db $41, $11
	dw @song0ref3357
	db $4e, $ff, $81, $81
	db $41, $0b
	dw @song0ref3398
@song0ref3864:
	db $4e, $ff, $83, $76, $2e, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $30
	db $41, $0b
	dw @song0ref3605
@song0ref3885:
	db $76, $35
@song0ref3887:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $4e, $fe, $3a, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e
	db $fe, $81, $76, $4e, $ff, $35
	db $41, $0b
	dw @song0ref3605
	db $76, $30, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $2e
	db $41, $0a
	dw @song0ref3400
	db $4e, $ff, $83, $76, $25
	db $41, $0a
	dw @song0ref3374
	db $4e, $ff, $81, $76, $22
	db $41, $0a
	dw @song0ref3026
	db $41, $0e
	dw @song0ref3505
	db $41, $0b
	dw @song0ref3246
	db $76, $4e, $fe, $0d
	db $41, $0b
	dw @song0ref3784
	db $76, $0a
	db $41, $0b
	dw @song0ref3300
	db $76, $4e, $ff, $12
	db $41, $0a
	dw @song0ref2983
	db $4e, $ff, $81, $76, $16, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $81, $76, $4e, $fe, $19, $81, $75, $83
	db $4e, $ff, $83, $74, $83, $4e, $fe, $81, $76, $4e, $ff, $1e
	db $41, $0b
	dw @song0ref3039
	db $76, $22
	db $41, $0b
	dw @song0ref3387
	db $76, $2a
	db $41, $0b
	dw @song0ref3592
	db $76, $2e
	db $41, $0b
	dw @song0ref3108
	db $76, $36
	db $41, $0b
	dw @song0ref3644
@song0ref4038:
	db $76, $4e, $fe, $3a, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $81, $76, $4e, $ff, $38, $81, $75, $83, $4e, $00
	db $83, $74, $83, $4e, $ff, $83, $76, $36
	db $41, $0b
	dw @song0ref3108
	db $76, $2e
	db $41, $0b
	dw @song0ref3592
	db $76, $2a
	db $41, $0b
	dw @song0ref3052
@song0ref4083:
	db $76, $22
@song0ref4085:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $20, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83
	db $76, $1e
	db $41, $0b
	dw @song0ref3713
@song0ref4114:
	db $76, $4e, $ff, $16
@song0ref4118:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $14, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81
	db $76, $12, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $4e, $fe, $0d
	db $41, $0b
	dw @song0ref3287
	db $76, $4e, $ff, $0f
	db $41, $0a
	dw @song0ref4118
	db $41, $08
	dw @song0ref3336
	db $41, $0b
	dw @song0ref3700
	db $76, $20
	db $41, $11
	dw @song0ref3361
@song0ref4180:
	db $76, $4e, $00, $27, $81, $75, $83, $4e, $01, $83, $74, $83, $4e, $00, $81, $76, $4e, $ff, $2c, $81, $75, $83, $4e, $00
	db $83, $74, $83
	db $41, $08
	dw @song0ref3864
	db $41, $0b
	dw @song0ref3121
	db $76, $38
	db $41, $0b
	dw @song0ref3887
	db $76, $4e, $ff, $3c
	db $41, $0b
	dw @song0ref3444
	db $76, $4e, $ff, $38
	db $41, $0b
	dw @song0ref3618
	db $76, $30
	db $41, $0b
	dw @song0ref3413
@song0ref4237:
	db $76, $2c
@song0ref4239:
	db $81, $75, $83
@song0ref4242:
	db $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $4e, $00, $27, $81, $75, $83, $4e, $01, $83, $74, $83, $4e, $00, $83, $76
	db $4e, $ff, $24, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $22
	db $41, $0b
	dw @song0ref3039
	db $76, $1b, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $18
	db $41, $0a
	dw @song0ref3825
	db $4e, $ff, $83, $76, $14
	db $41, $0b
	dw @song0ref3259
@song0ref4311:
	db $76, $09
@song0ref4313:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $4e, $fe, $0d, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e
	db $fe, $83, $76, $4e, $ff, $10
	db $41, $0b
	dw @song0ref4118
	db $76, $4e, $fe, $15, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $83, $76, $19, $81, $75, $83, $4e, $ff, $83, $74
	db $83, $4e, $fe, $81, $76, $4e, $ff, $1c
	db $41, $0b
	dw @song0ref3039
	db $76, $21
	db $41, $0b
	dw @song0ref3387
	db $76, $28
	db $41, $0b
	dw @song0ref3095
	db $76, $2d
	db $41, $0b
	dw @song0ref3605
	db $76, $34
	db $41, $0b
	dw @song0ref3147
	db $76, $39
	db $41, $0b
	dw @song0ref3147
	db $76, $34
	db $41, $0b
	dw @song0ref3605
	db $76, $2d
	db $41, $0b
	dw @song0ref3095
	db $76, $28
	db $41, $0b
	dw @song0ref3052
	db $76, $21
	db $41, $0b
	dw @song0ref4085
	db $76, $1c
	db $41, $0b
	dw @song0ref3713
	db $76, $15
	db $41, $0b
	dw @song0ref3231
	db $76, $10
	db $41, $0b
	dw @song0ref4313
@song0ref4441:
	db $76, $0b
@song0ref4443:
	db $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $81, $76, $4e, $ff, $0f, $81, $75, $83, $4e, $00, $83, $74, $83, $4e
	db $ff, $83, $76, $12
	db $41, $0a
	dw @song0ref3825
	db $4e, $ff, $83, $76, $4e, $fe, $17
	db $41, $0b
	dw @song0ref3011
@song0ref4484:
	db $76, $1e
@song0ref4486:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $22, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83
	db $76, $23
	db $41, $0a
	dw @song0ref4239
	db $4e, $00, $81, $76, $4e, $ff, $2a
@song0ref4522:
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $2e, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81
	db $76, $2f
	db $41, $0b
	dw @song0ref3121
	db $76, $36
	db $41, $0b
	dw @song0ref3887
	db $76, $4e, $ff, $3b
	db $41, $0a
	dw @song0ref3887
	db $4e, $fe, $83, $76, $4e, $ff, $36
	db $41, $0a
	dw @song0ref3121
	db $4e, $ff, $83, $76, $2f
	db $41, $0a
	dw @song0ref4522
	db $4e, $ff, $83, $76, $2a
	db $41, $0a
	dw @song0ref3065
@song0ref4589:
	db $4e, $00, $85, $76, $4e, $ff, $23, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $85, $76, $22, $81, $75, $83, $4e
	db $00, $83, $74, $83, $4e, $ff, $85, $76, $1e, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $85, $76, $1b, $81, $75
	db $83, $4e, $00, $83, $74, $83, $4e, $ff, $87, $76, $4e, $fe, $17, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $87
	db $76, $4e, $ff, $16, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $87, $76, $12, $81, $75, $83, $4e, $00, $83, $74
	db $83, $4e, $ff, $87, $73, $4e, $00, $81, $76, $4e, $ff, $0f, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $87, $76
	db $4e, $fe
	db $41, $1d
	dw @song0ref2954
	db $4e, $fe, $83, $76, $4e, $ff, $1b, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81
	db $41, $0b
	dw @song0ref3037
	db $4e, $ff, $83, $76, $25
	db $41, $0a
	dw @song0ref4239
	db $41, $26
	dw @song0ref3088
	db $41, $0b
	dw @song0ref3147
	db $76, $35
	db $41, $0b
	dw @song0ref3121
	db $76, $31
	db $41, $0b
	dw @song0ref3095
	db $76, $29
	db $41, $0b
	dw @song0ref3065
	db $76, $4e, $ff, $25
	db $41, $0b
	dw @song0ref3039
	db $41, $11
	dw @song0ref3698
	db $41, $32
	dw @song0ref3239
	db $41, $0b
	dw @song0ref3216
	db $41, $1d
	dw @song0ref3357
	db $41, $08
	dw @song0ref3864
	db $41, $0b
	dw @song0ref3605
	db $41, $0d
	dw @song0ref3442
	db $41, $0b
	dw @song0ref3108
	db $76, $30
	db $41, $0b
	dw @song0ref3413
	db $76, $29
	db $41, $0b
	dw @song0ref3052
	db $76, $24
	db $41, $0b
	dw @song0ref4486
	db $76, $1d
	db $41, $0b
	dw @song0ref3713
	db $76, $4e, $ff, $18
	db $41, $0a
	dw @song0ref3825
	db $4e, $ff, $83, $76, $11
	db $41, $0b
	dw @song0ref4313
	db $41, $0c
	dw @song0ref3795
	db $76, $4e, $ff, $0f
	db $41, $0a
	dw @song0ref3743
	db $4e, $ff, $81, $76, $14
	db $41, $0b
	dw @song0ref3216
	db $41, $0b
	dw @song0ref3022
	db $4e, $ff, $81, $76, $20
	db $41, $0b
	dw @song0ref3387
	db $41, $2b
	dw @song0ref3573
	db $41, $0b
	dw @song0ref3644
	db $76, $35
	db $41, $0b
	dw @song0ref3618
	db $76, $31
	db $41, $0a
	dw @song0ref3592
	db $4e, $ff, $81, $76, $29
	db $41, $0b
	dw @song0ref3065
	db $76, $4e, $ff, $25
	db $41, $0b
	dw @song0ref3039
	db $41, $41
	dw @song0ref3698
	db $4e, $ff, $83, $76, $18
	db $41, $0b
	dw @song0ref3713
	db $76, $4e, $ff, $1d
	db $41, $0a
	dw @song0ref4486
	db $41, $12
	dw @song0ref3382
	db $41, $08
	dw @song0ref3864
	db $41, $0b
	dw @song0ref3605
	db $41, $0d
	dw @song0ref3885
	db $41, $0b
	dw @song0ref3605
	db $76, $30
	db $41, $0b
	dw @song0ref4522
	db $76, $29
	db $41, $0b
	dw @song0ref3387
	db $76, $24
	db $41, $0b
	dw @song0ref3361
	db $76, $1d
	db $41, $0b
	dw @song0ref3216
	db $76, $4e, $ff, $18
	db $41, $0a
	dw @song0ref3825
	db $4e, $ff, $83, $76, $11
	db $41, $0b
	dw @song0ref4313
	db $76, $0c, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $81, $76, $0a
	db $41, $0b
	dw @song0ref3300
	db $76, $4e, $ff, $12
	db $41, $0a
	dw @song0ref2983
	db $4e, $ff, $81, $76, $16
	db $41, $0b
	dw @song0ref3216
	db $76, $4e, $ff, $1e
	db $41, $0b
	dw @song0ref3039
	db $76, $22
	db $41, $0b
	dw @song0ref3387
	db $76, $2a
	db $41, $0b
	dw @song0ref3095
	db $76, $2e
	db $41, $0b
	dw @song0ref3605
	db $76, $36
	db $41, $0b
	dw @song0ref3644
	db $41, $0d
	dw @song0ref4038
	db $41, $0b
	dw @song0ref3108
	db $76, $2e
	db $41, $0b
	dw @song0ref3592
	db $76, $2a
	db $41, $0b
	dw @song0ref3052
	db $41, $0d
	dw @song0ref4083
	db $41, $0b
	dw @song0ref3713
	db $41, $0b
	dw @song0ref4114
	db $4e, $ff, $83, $76, $12
	db $41, $0b
	dw @song0ref4313
	db $76, $0c
	db $41, $0a
	dw @song0ref4443
	db $4e, $ff, $81, $76, $14
	db $41, $0c
	dw @song0ref3328
	db $41, $0b
	dw @song0ref3700
	db $76, $20
	db $41, $11
	dw @song0ref3361
	db $41, $0b
	dw @song0ref4180
	db $41, $08
	dw @song0ref3864
	db $41, $0b
	dw @song0ref3121
	db $76, $38
	db $41, $0b
	dw @song0ref3887
	db $76, $4e, $ff, $3c
	db $41, $0b
	dw @song0ref3887
	db $76, $4e, $ff, $38
	db $41, $0b
	dw @song0ref3121
	db $76, $30
	db $41, $0b
	dw @song0ref3413
	db $41, $13
	dw @song0ref4237
	db $41, $0b
	dw @song0ref3039
	db $76, $1b, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $18
	db $41, $0a
	dw @song0ref3825
	db $4e, $ff, $83, $76, $14
	db $41, $0b
	dw @song0ref3259
	db $41, $0d
	dw @song0ref4311
	db $41, $0a
	dw @song0ref4118
@song0ref5143:
	db $4e, $ff, $83, $76, $4e, $fe, $15, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $81, $76, $19, $81, $75, $83, $4e
	db $ff, $83, $74, $83, $4e, $fe, $83, $76, $4e, $ff, $1c
	db $41, $0a
	dw @song0ref4085
	db $4e, $ff, $81, $76, $21
	db $41, $0b
	dw @song0ref3387
	db $76, $28
	db $41, $0b
	dw @song0ref3095
	db $76, $2d
	db $41, $0b
	dw @song0ref3605
	db $76, $34
	db $41, $0b
	dw @song0ref3147
	db $76, $39
	db $41, $0b
	dw @song0ref3147
	db $76, $34
	db $41, $0b
	dw @song0ref3605
	db $76, $2d
	db $41, $0b
	dw @song0ref3095
	db $76, $28
	db $41, $0b
	dw @song0ref3387
	db $76, $21
	db $41, $0b
	dw @song0ref3039
	db $76, $1c
	db $41, $0b
	dw @song0ref3713
	db $76, $15
	db $41, $0b
	dw @song0ref3231
	db $76, $10
	db $41, $0b
	dw @song0ref4313
	db $41, $0d
	dw @song0ref4441
	db $41, $0a
	dw @song0ref3825
	db $4e, $ff, $83, $76, $4e, $fe, $17
	db $41, $0b
	dw @song0ref3011
	db $41, $0d
	dw @song0ref4484
	db $41, $0b
	dw @song0ref4239
	db $76, $4e, $ff, $2a
	db $41, $0b
	dw @song0ref3413
	db $76, $2f
	db $41, $0a
	dw @song0ref3618
	db $4e, $ff, $81, $76, $36
	db $41, $0a
	dw @song0ref3887
	db $4e, $fe, $83, $76, $4e, $ff, $3b
	db $41, $0b
	dw @song0ref3444
	db $76, $4e, $ff, $36
	db $41, $0a
	dw @song0ref3121
	db $4e, $ff, $83, $76, $2f
	db $41, $0a
	dw @song0ref4522
	db $4e, $ff, $83, $76, $2a
	db $41, $0a
	dw @song0ref3065
	db $41, $32
	dw @song0ref4589
	db $76, $4e, $fe
	db $41, $11
	dw @song0ref2954
	db $4e, $ff, $85, $76, $14
	db $41, $0a
	dw @song0ref3216
	db $4e, $fe, $83, $76, $4e, $ff, $1b, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81
	db $41, $0b
	dw @song0ref3037
	db $4e, $ff, $83, $76, $25
	db $41, $0a
	dw @song0ref4239
	db $41, $26
	dw @song0ref3088
	db $41, $0b
	dw @song0ref3147
	db $76, $35
	db $41, $0b
	dw @song0ref3121
	db $76, $31
	db $41, $0b
	dw @song0ref3095
	db $76, $29
	db $41, $0b
	dw @song0ref3065
	db $76, $4e, $ff, $25
	db $41, $0b
	dw @song0ref3039
	db $41, $11
	dw @song0ref3698
	db $41, $32
	dw @song0ref3239
	db $41, $0b
	dw @song0ref3216
	db $41, $1d
	dw @song0ref3357
	db $41, $08
	dw @song0ref3864
	db $41, $0b
	dw @song0ref3605
	db $41, $0d
	dw @song0ref3442
	db $41, $0b
	dw @song0ref3108
	db $76, $30
	db $41, $0b
	dw @song0ref3413
	db $76, $29
	db $41, $0b
	dw @song0ref3052
	db $76, $24
	db $41, $0b
	dw @song0ref4486
	db $76, $1d
	db $41, $0b
	dw @song0ref3713
	db $76, $4e, $ff, $18
	db $41, $0a
	dw @song0ref3825
	db $4e, $ff, $83, $76, $11
	db $41, $0b
	dw @song0ref4313
	db $41, $0c
	dw @song0ref3795
	db $76, $4e, $ff, $0f
	db $41, $0a
	dw @song0ref3743
	db $4e, $ff, $81, $76, $14
	db $41, $0b
	dw @song0ref3216
	db $41, $0b
	dw @song0ref3022
	db $4e, $ff, $81, $76, $20
	db $41, $0b
	dw @song0ref3387
	db $41, $2b
	dw @song0ref3573
	db $41, $0b
	dw @song0ref3644
	db $76, $35
	db $41, $0b
	dw @song0ref3618
	db $76, $31
	db $41, $0a
	dw @song0ref3592
	db $4e, $ff, $81, $76, $29
	db $41, $0b
	dw @song0ref3065
	db $76, $4e, $ff, $25
	db $41, $0b
	dw @song0ref3039
	db $41, $41
	dw @song0ref3698
	db $4e, $ff, $83, $76, $18
	db $41, $0b
	dw @song0ref3713
	db $76, $4e, $ff, $1d
	db $41, $0a
	dw @song0ref4486
	db $41, $12
	dw @song0ref3382
	db $41, $08
	dw @song0ref3864
	db $41, $0b
	dw @song0ref3605
	db $41, $0d
	dw @song0ref3885
	db $41, $0b
	dw @song0ref3605
	db $76, $30
	db $41, $0b
	dw @song0ref4522
	db $76, $29
	db $41, $0b
	dw @song0ref3387
	db $76, $24
	db $41, $0b
	dw @song0ref3361
	db $76, $1d
	db $41, $0b
	dw @song0ref3216
	db $76, $4e, $ff, $18
	db $41, $0a
	dw @song0ref3825
	db $4e, $ff, $83, $76, $11
	db $41, $0b
	dw @song0ref4313
	db $76, $0c, $81, $75, $83, $4e, $ff, $83, $74, $83, $4e, $fe, $81, $76, $0a, $81, $75, $81, $81
	db $41, $09
	dw @song0ref3303
	db $76, $4e, $ff, $12
	db $41, $0a
	dw @song0ref2983
	db $4e, $ff, $81, $76, $16
	db $41, $0b
	dw @song0ref3216
	db $76, $4e, $ff, $1e
	db $41, $0b
	dw @song0ref3039
	db $76, $22
	db $41, $0b
	dw @song0ref3387
	db $76, $2a
	db $41, $0b
	dw @song0ref3095
	db $76, $2e
	db $41, $0b
	dw @song0ref3605
	db $76, $36
	db $41, $0b
	dw @song0ref3644
	db $41, $0d
	dw @song0ref4038
	db $41, $0b
	dw @song0ref3108
	db $76, $2e
	db $41, $0b
	dw @song0ref3592
	db $76, $2a
	db $41, $0b
	dw @song0ref3052
	db $41, $0d
	dw @song0ref4083
	db $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $81, $76, $4e, $fe, $19, $81, $75, $81, $81, $4e, $ff, $83, $74, $83
	db $4e, $fe, $83
	db $41, $0b
	dw @song0ref4114
	db $4e, $ff, $83, $76, $12
	db $41, $0b
	dw @song0ref4313
	db $76, $0c
	db $41, $0a
	dw @song0ref4443
	db $4e, $ff, $81, $76, $14
	db $41, $0c
	dw @song0ref3328
	db $41, $0b
	dw @song0ref3700
	db $76, $20
	db $41, $11
	dw @song0ref3361
	db $41, $0b
	dw @song0ref4180
	db $41, $08
	dw @song0ref3864
	db $41, $0b
	dw @song0ref3121
	db $76, $38
	db $41, $0b
	dw @song0ref3887
	db $76, $4e, $ff, $3c
	db $41, $0b
	dw @song0ref3887
	db $76, $4e, $ff, $38
	db $41, $0b
	dw @song0ref3121
	db $76, $30
	db $41, $0b
	dw @song0ref3413
	db $76, $2c, $81, $75, $81, $81
	db $41, $10
	dw @song0ref4242
	db $41, $0b
	dw @song0ref3039
	db $76, $1b, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $18
	db $41, $0a
	dw @song0ref3825
	db $4e, $ff, $83, $76, $14
	db $41, $0b
	dw @song0ref3259
	db $41, $0d
	dw @song0ref4311
	db $41, $0a
	dw @song0ref4118
	db $41, $0e
	dw @song0ref5143
	db $41, $0a
	dw @song0ref4085
	db $4e, $ff, $81, $76, $21
	db $41, $0b
	dw @song0ref3387
	db $76, $28
	db $41, $0b
	dw @song0ref3095
	db $76, $2d
	db $41, $0b
	dw @song0ref3605
	db $76, $34
	db $41, $0b
	dw @song0ref3147
	db $76, $39, $81, $75, $83, $4e, $00, $83, $74, $83, $4e, $ff, $83, $76, $38, $81, $75, $81, $81, $4e, $00, $83, $74, $83
	db $4e, $ff, $81, $76, $34
	db $41, $0b
	dw @song0ref3605
	db $76, $2d
	db $41, $0b
	dw @song0ref3095
	db $76, $28
	db $41, $0b
	dw @song0ref3387
	db $76, $21
	db $41, $0b
	dw @song0ref3039
	db $76, $1c
	db $41, $0b
	dw @song0ref3713
	db $76, $15
	db $41, $0b
	dw @song0ref3231
	db $76, $10
	db $41, $0b
	dw @song0ref4313
	db $41, $0d
	dw @song0ref4441
	db $41, $0a
	dw @song0ref3825
	db $4e, $ff, $83, $76, $4e, $fe, $17
	db $41, $0b
	dw @song0ref3011
	db $41, $0d
	dw @song0ref4484
	db $41, $0b
	dw @song0ref4239
	db $76, $4e, $ff, $2a
	db $41, $0b
	dw @song0ref3413
	db $76, $2f, $81, $75, $81, $81
	db $41, $08
	dw @song0ref3621
	db $4e, $ff, $81, $76, $36
	db $41, $0a
	dw @song0ref3887
	db $4e, $fe, $83, $76, $4e, $ff, $3b, $81, $75, $83, $4e, $00, $83, $74, $ff, $ff, $ff, $ad, $42
	dw @song0ch1loop
@song0ch4:
@song0ch3:
@song0ch2:
@song0ch2loop:
@song0ref5960:
	db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $41, $08
	dw @song0ref5960
	db $ff, $ff, $ff, $ff, $42
	dw @song0ch2loop
