; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Duck Tales:
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1

music_data_duck_tales:
	db 1
	dw @instruments
	dw @samples-4
; 00 : The Moon
	dw @song0ch0
	dw @song0ch1
	dw @song0ch2
	dw @song0ch3
	dw @song0ch4
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env10,@env6,@env8,@env0 ; 00 : DrumHi
	dw @env12,@env6,@env8,@env0 ; 01 : DrumLo
	dw @env16,@env6,@env8,@env0 ; 02 : DrumMed
	dw @env14,@env6,@env11,@env0 ; 03 : BleepIntro
	dw @env17,@env6,@env1,@env0 ; 04 : Bleep
	dw @env7,@env6,@env8,@env0 ; 05 : LeadLo
	dw @env5,@env6,@env1,@env0 ; 06 : LeadIntro
	dw @env3,@env6,@env8,@env0 ; 07 : Lead
	dw @env2,@env6,@env8,@env0 ; 08 : Bass
	dw @env13,@env6,@env8,@env0 ; 09 : DrumIntro

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c3,$7f,$00,$00
@env2:
	db $00,$cf,$7f,$00,$02
@env3:
	db $00,$ca,$7f,$00,$02
@env4:
	db $00,$c0,$bf,$be,$bf,$c0,$c1,$c2,$c1,$00,$01
@env5:
	db $00,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$00,$0a
@env6:
	db $c0,$7f,$00,$01
@env7:
	db $00,$c7,$7f,$00,$02
@env8:
	db $7f,$00,$00
@env9:
	db $00,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$00,$01
@env10:
	db $00,$ca,$c4,$00,$02
@env11:
	db $c1,$7f,$00,$00
@env12:
	db $00,$ca,$02,$c2,$00,$03
@env13:
	db $00,$ca,$02,$c5,$00,$03
@env14:
	db $00,$c7,$06,$c1,$00,$03
@env15:
	db $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env16:
	db $00,$ca,$02,$c6,$03,$c2,$00,$05
@env17:
	db $00,$c7,$02,$c5,$03,$c1,$00,$05

@samples:

@tempo_env_1_mid:
	db $03,$05,$80

@song0ch0:
	db $ff, $ff, $ab, $48, $8c, $26, $cd, $49, <(@env15), >(@env15), $e1, $00, $49, <(@env0), >(@env0), $4a, $8c, $2b, $a3, $00
	db $2d, $a3, $00, $30, $a3, $00, $48, $30, $b7, $00, $2f, $8f, $00, $2f, $b9, $49, <(@env15), >(@env15), $cd, $00, $49, <(@env0)
	db >(@env0), $4a, $8c, $2d, $a3, $00, $2b, $a3, $00, $48, $32, $f3, $00, $2b, $f3, $00, $37, $b9, $48, $bb, $49, <(@env4)
	db >(@env4), $ff, $b1, $00, $49, <(@env0), >(@env0), $4a, $8c, $39, $a3, $00, $37, $8f, $00, $48, $3e, $ff, $9d, $49, <(@env4)
	db >(@env4), $ff, $9d, $49, <(@env0), >(@env0), $4a, $00
@song0ch0loop:
	db $47, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $cf, $8e, $23, $8f, $00, $24, $8f, $00, $26, $8f, $00, $26, $b7, $00, $2b
	db $a3, $00, $2a, $a3, $00, $2b, $a3, $00, $48, $2d, $a3, $00, $2f, $8f, $00, $2b, $cd, $49, <(@env9), >(@env9), $ff, $89
	db $00, $49, <(@env0), >(@env0), $4a, $8e, $2a, $8f, $00, $2b, $8f, $00, $48, $32, $b7, $00, $2b, $8f, $00, $2b, $cd, $49
	db <(@env9), >(@env9), $f7, $49, <(@env0), >(@env0), $4a, $91, $00, $8e, $2b, $8f, $00, $48, $2b, $cb, $00, $93, $2d, $8f
	db $00, $2b, $8f, $00, $2a, $cd, $49, <(@env9), >(@env9), $e1, $00, $48, $49, <(@env0), >(@env0), $4a, $8e, $23, $cb, $00
	db $93, $21, $8f, $00, $1f, $8f, $00, $26, $cb, $00, $93, $2b, $a3, $00, $2d, $a3, $00, $48, $30, $b7, $00, $2f, $8f, $00
	db $2f, $cd, $49, <(@env9), >(@env9), $cd, $00, $49, <(@env0), >(@env0), $4a, $8e, $32, $a3, $00, $30, $a3, $00, $48, $2f
	db $8f, $00, $30, $8f, $00, $2f, $8f, $00, $2b, $a3, $00, $26, $cb, $00, $2d, $8f, $00, $2b, $8f, $00, $2a, $8f, $00, $28
	db $8f, $00, $2a, $b7, $00, $48, $2b, $8f, $00, $a7, $2b, $8f, $00, $a7, $2b, $a3, $00, $8d, $72, $50, $f8, $23, $32, $8d
	db $73, $8f, $75, $8f, $76, $8f, $77, $8f, $79, $8f, $7a, $8f, $7c, $8f, $7e, $8f, $00, $48, $7f
@song0ref308:
	db $2b, $8f, $00, $2b, $8f, $00, $a7, $2d, $8f, $00, $2d, $8f, $00, $93, $29, $cb, $00, $26, $a3, $00, $29, $8f, $00, $24
	db $83, $25, $83, $00, $24, $81, $00, $22, $8f, $00, $48, $24, $a3, $00, $22, $8f, $00, $24, $8f, $00, $93, $22, $8f, $00
	db $93, $26, $ff, $9b, $00, $93, $48
	db $41, $0e
	dw @song0ref308
	db $2e, $a3, $00, $29, $a3, $00, $29, $a3, $00, $29, $8f, $00, $2e, $8f, $00, $30, $91, $48, $f5, $00, $2e, $8f, $00, $32
	db $f3, $00, $32, $8f, $00, $32, $8f, $00, $32, $91, $48, $cf, $49, <(@env9), >(@env9), $ff, $9d, $00, $49, <(@env0), >(@env0)
	db $4a, $8e, $0f, $a3, $00, $11, $a3, $00, $42
	dw @song0ch0loop
@song0ch1:
	db $86
@song0ref423:
	db $2b, $8f, $00, $32, $8f, $00, $37, $8f, $00, $39, $8f, $00, $32, $8f, $00, $37, $8f, $00, $39
@song0ref442:
	db $8f, $00, $3c, $8f, $00, $32, $8f, $00, $3c, $8f, $00, $3b, $8f, $00, $32, $8f, $00, $3b, $8f, $00, $39, $8f, $00, $37
	db $8f, $00
	db $41, $2d
	dw @song0ref423
	db $41, $2d
	dw @song0ref423
	db $41, $2d
	dw @song0ref423
	db $41, $2d
	dw @song0ref423
	db $88
	db $41, $15
	dw @song0ref423
	db $32
	db $41, $1a
	dw @song0ref442
@song0ch1loop:
	db $41, $15
	dw @song0ref423
	db $32
	db $41, $1a
	dw @song0ref442
	db $41, $15
	dw @song0ref423
	db $32
	db $41, $1a
	dw @song0ref442
	db $41, $15
	dw @song0ref423
	db $32
	db $41, $1a
	dw @song0ref442
	db $41, $15
	dw @song0ref423
	db $32
	db $41, $1a
	dw @song0ref442
	db $41, $15
	dw @song0ref423
	db $32
	db $41, $1a
	dw @song0ref442
	db $41, $15
	dw @song0ref423
	db $32
	db $41, $1a
	dw @song0ref442
	db $41, $15
	dw @song0ref423
	db $32
	db $41, $1a
	dw @song0ref442
	db $37, $8f, $00, $2e, $8f, $00, $33, $8f, $00, $39, $8f, $00, $30, $8f, $00, $39, $8f, $00, $3c, $8f, $00, $3b, $8f, $00
	db $37, $8f, $00, $32, $8f, $00, $30, $8f, $00, $2f, $8f, $00, $2b, $8f, $00, $26, $8f, $00, $24, $8f, $00, $23, $8f, $00
	db $8a, $22, $8f, $00, $22, $8f, $00, $a7, $24, $8f, $00, $24, $8f, $00, $93, $22, $a3, $00, $86, $2d, $8f, $00, $2e, $8f
	db $00, $35, $8f, $00, $93, $39, $8f, $00, $3a, $8f, $00, $40, $4d, $8f, $00, $8a, $1b, $a3, $00, $1b, $8f, $00, $1b, $8f
	db $00, $93, $1b, $8f, $00, $93, $1e, $ff, $9b, $00, $93, $27, $8f, $00, $27, $8f, $00, $a7, $24, $8f, $00, $24, $8f, $00
	db $93, $26, $a3, $00, $26, $a3, $00, $26, $a3, $00, $26, $8f, $00, $29, $8f, $00, $2b, $91, $e1, $00, $93, $2b, $8f, $00
	db $2a, $f3, $00, $2a, $8f, $00, $2a, $8f, $00, $2b, $8f, $00, $88
	db $41, $15
	dw @song0ref423
	db $32
	db $41, $1a
	dw @song0ref442
	db $42
	dw @song0ch1loop
@song0ch2:
	db $ff, $ff, $ab, $90, $1f, $b7, $00, $26, $b7, $00, $2b, $ff, $9b, $00, $93, $1d, $b7, $00, $24, $b7, $00, $29, $ff, $9b
	db $00, $93, $1c, $b7, $00, $23, $b7, $00, $28, $ff, $9b, $00, $93, $1b, $b7, $00, $22, $b7, $00, $27, $ff, $9b, $00, $93
@song0ref753:
	db $2b, $8f, $00, $2b, $8f, $00, $2b, $8f, $00, $2b, $8f, $00
	db $41, $0c
	dw @song0ref753
	db $41, $0c
	dw @song0ref753
	db $41, $0c
	dw @song0ref753
@song0ch2loop:
	db $41, $0c
	dw @song0ref753
	db $41, $0c
	dw @song0ref753
@song0ref781:
	db $2a, $8f, $00, $2a, $8f, $00, $2a, $8f, $00, $2a, $8f, $00
	db $41, $0c
	dw @song0ref781
@song0ref796:
	db $28, $8f, $00, $28, $8f, $00, $28, $8f, $00, $28, $8f, $00
	db $41, $0c
	dw @song0ref796
@song0ref811:
	db $26, $8f, $00, $26, $8f, $00, $26, $8f, $00, $26, $8f, $00
	db $41, $0c
	dw @song0ref811
@song0ref826:
	db $24, $8f, $00, $24, $8f, $00, $24, $8f, $00, $24, $8f, $00
	db $41, $0c
	dw @song0ref826
@song0ref841:
	db $25, $8f, $00, $25, $8f, $00, $25, $8f, $00, $25, $8f, $00
	db $41, $0c
	dw @song0ref841
	db $41, $0c
	dw @song0ref811
	db $41, $0c
	dw @song0ref811
	db $41, $0c
	dw @song0ref811
	db $41, $0c
	dw @song0ref811
	db $41, $0c
	dw @song0ref753
	db $41, $0c
	dw @song0ref753
@song0ref874:
	db $29, $8f, $00, $29, $8f, $00, $29, $8f, $00, $29, $8f, $00
	db $41, $0c
	dw @song0ref874
	db $41, $0c
	dw @song0ref796
	db $41, $0c
	dw @song0ref796
@song0ref895:
	db $27, $8f, $00, $27, $8f, $00, $27, $8f, $00, $27, $8f, $00
	db $41, $0c
	dw @song0ref895
	db $41, $0c
	dw @song0ref811
	db $41, $0c
	dw @song0ref811
	db $41, $0c
	dw @song0ref841
	db $41, $0c
	dw @song0ref811
	db $27, $8f, $00, $a7, $29, $8f, $00, $a7, $2b, $b7, $00, $1f, $8f, $00, $1f, $8f, $00, $1f, $8f, $00, $1f, $8f, $00, $1f
	db $8f, $00, $1f, $8f, $00, $1f, $8f, $00
@song0ref954:
	db $24, $8f, $00, $24, $8f, $00, $a7, $29, $8f, $00, $29, $8f, $00, $93, $22, $a3, $00, $22, $8f, $00, $22, $8f, $00, $22
	db $8f, $00, $22, $8f, $00, $22, $8f, $00, $22, $8f, $00, $22, $8f, $00
	db $41, $0c
	dw @song0ref826
	db $41, $0c
	dw @song0ref826
	db $41, $0c
	dw @song0ref811
	db $41, $0c
	dw @song0ref811
	db $41, $26
	dw @song0ref954
	db $41, $0c
	dw @song0ref826
	db $41, $0c
	dw @song0ref826
	db $41, $0c
	dw @song0ref811
	db $41, $0c
	dw @song0ref811
	db $41, $0c
	dw @song0ref895
	db $41, $0c
	dw @song0ref895
	db $27, $8f, $00, $bb, $27, $a3, $00, $29, $a3, $00, $42
	dw @song0ch2loop
@song0ch3:
@song0ref1038:
	db $ff, $ff, $ab, $ff, $ff, $ab, $ff, $ff, $ab, $ff, $ff, $ab, $ff, $db, $92, $19, $8b, $00, $83, $14, $8b, $00, $83, $19
	db $8b, $00, $83, $14, $8b, $00, $83
@song0ref1069:
	db $82, $14, $8b, $00, $83, $80, $20, $83, $00, $8b, $84, $19, $8f, $00, $80, $20, $83, $00, $8b
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
@song0ref1094:
	db $82, $14, $8b, $00, $83, $80, $20, $83, $00, $8b, $84, $19, $8f, $00, $19, $8f, $00
@song0ch3loop:
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0f
	dw @song0ref1069
	db $41, $0e
	dw @song0ref1094
	db $42
	dw @song0ch3loop
@song0ch4:
	db $41, $0d
	dw @song0ref1038
	db $ff, $ab, $ff, $ff, $bf
@song0ch4loop:
@song0ref1280:
	db $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	db $41, $0c
	dw @song0ref1280
	db $41, $0c
	dw @song0ref1280
	db $ff, $ff, $bf, $42
	dw @song0ch4loop
