; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for :
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1

song_of_storm:
	db 1
	dw @instruments
	dw @samples-4
; 00 : Song 1
	dw @song0ch0
	dw @song0ch1
	dw @song0ch2
	dw @song0ch3
	dw @song0ch4
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env1,@env2,@env4,@env0 ; 00 : Duty 2
	dw @env1,@env2,@env5,@env0 ; 01 : Duty 1
	dw @env1,@env2,@env3,@env0 ; 02 : Duty 0

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $00,$cf,$7f,$00,$02
@env2:
	db $c0,$7f,$00,$01
@env3:
	db $7f,$00,$00
@env4:
	db $c2,$7f,$00,$00
@env5:
	db $c1,$7f,$00,$00

@samples:

@tempo_env_1_mid:
	db $03,$05,$80

@song0ch0:
@song0ch0loop:
	db $47, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $bf, $00, $ff, $ff, $ff, $bd, $48, $ff, $ff, $df
@song0ref15:
	db $75, $80, $1b, $77, $81, $79, $82, $1b, $87, $72, $83
@song0ref26:
	db $75, $80, $1e, $77, $81, $79, $82, $1e, $87, $72, $83, $75, $80, $27, $77, $81, $79, $82, $27
@song0ref45:
	db $9d
@song0ref46:
	db $4e, $fd, $81, $4e, $fc, $83, $4e, $ff, $81, $4e, $01, $81, $4e, $04, $83, $4e, $03, $81, $4e, $00, $81, $4e, $fe, $81
	db $4e, $fc, $83, $4e, $ff, $81, $4e, $00, $81, $4e, $03, $81, $4e, $04, $81, $72, $4e, $03, $81, $4e, $00, $81
	db $41, $0d
	dw @song0ref15
	db $89, $48, $93
	db $41, $0f
	dw @song0ref46
@song0ref101:
	db $75, $80, $29, $77, $81, $79, $82, $29, $9d, $4e, $fd, $81, $4e, $fc, $83, $4e, $ff, $81, $4e, $01, $81, $4e, $04, $83
	db $72, $4e, $03, $81, $4e, $00, $81
@song0ref132:
	db $75, $80, $2a, $77, $81, $79, $82, $2a, $87, $72, $83, $75, $80, $29, $77, $81, $79, $82, $29, $87, $72, $83
	db $41, $0a
	dw @song0ref132
@song0ref157:
	db $75, $80, $25, $77, $81, $79, $82, $25, $87, $72, $83, $75, $80, $22, $77, $81, $79, $82, $22
	db $41, $10
	dw @song0ref45
@song0ref179:
	db $75, $80, $22, $77, $81, $79, $82, $22
@song0ref187:
	db $99
@song0ref188:
	db $72, $83, $75, $80, $1b, $77, $81, $79, $82, $1b, $99, $72, $83, $75, $80, $1e, $77, $81, $79, $82, $1e, $87, $72, $83
	db $75, $80, $20, $77, $81, $79, $82, $20, $87, $72, $83, $75, $80, $22, $77, $81, $79, $82, $22
	db $41, $0e
	dw @song0ref45
@song0ref234:
	db $4e, $03, $81, $4e, $00, $81
@song0ref240:
	db $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $81, $4e, $03, $81, $4e, $04, $81, $4e, $03, $81, $4e, $00, $81
	db $4e, $ff, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $81, $4e, $03, $81, $4e, $04, $81, $72, $4e, $00, $83, $75, $80
	db $22, $77, $81, $79, $82, $22, $91, $48, $87
	db $41, $10
	dw @song0ref188
	db $75, $80, $1d, $77, $81, $79, $82, $1d
	db $41, $0e
	dw @song0ref45
	db $41, $11
	dw @song0ref234
	db $41, $1d
	dw @song0ref15
	db $41, $1d
	dw @song0ref15
	db $41, $15
	dw @song0ref101
	db $75, $80, $2a, $77, $81, $79, $82, $2a, $87, $48, $72, $83, $75, $80, $29, $77, $81, $79, $82, $29, $87, $72, $83
	db $41, $08
	dw @song0ref157
	db $41, $10
	dw @song0ref45
	db $41, $17
	dw @song0ref179
	db $41, $10
	dw @song0ref45
	db $41, $08
	dw @song0ref179
	db $9d
@song0ref362:
	db $78, $4e, $fd, $81, $4e, $fc, $83, $4e, $ff, $81, $4e, $01, $81, $4e, $04, $83, $4e, $03, $81, $4e, $00, $81, $77, $4e
	db $fe, $81, $4e, $fc, $83, $4e, $ff, $81, $4e, $00, $81, $4e, $03, $81, $4e, $04, $81, $4e, $03, $81, $4e, $00, $81, $76
	db $41, $08
	dw @song0ref240
@song0ref413:
	db $75, $4e, $ff, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $81, $4e, $03, $81, $4e, $04, $83, $4e, $01, $81, $74, $4e
	db $ff, $81, $4e, $fc, $83, $4e, $fd, $81, $4e, $00, $81, $4e, $02, $81, $4e, $04, $83, $4e, $01, $81, $73, $4e, $00, $81
	db $4e, $fd, $81, $4e, $fc, $81, $4e, $fd, $81, $4e, $00, $81, $4e, $02, $81, $4e, $04, $83, $4e, $02, $81, $72, $4e, $00
	db $81, $4e, $fd, $81, $4e, $fc, $81, $4e, $fd, $81, $4e, $00, $81, $4e, $01, $81, $4e, $04, $83, $4e, $02, $81, $4e, $00
	db $81, $4e, $fd, $81, $4e, $fc, $83, $4e, $ff, $81, $4e, $01, $81, $4e, $04, $83, $4e, $03, $81, $71, $4e, $00, $81, $4e
	db $fe, $81, $48, $4e, $fc, $83, $4e, $ff, $81, $4e, $00, $81, $4e, $03, $81, $4e, $04, $81
	db $41, $08
	dw @song0ref234
	db $00, $4e, $00, $ff, $ff, $ff, $df, $48, $ff, $a7
@song0ref564:
	db $75, $84, $1b, $77, $81, $75, $80, $2e, $79, $1b, $85, $72, $83, $75, $84, $1e, $77, $81, $75, $80, $31, $79, $1e, $85
	db $72, $83, $75, $84, $27, $77, $81, $75, $80, $3a, $79, $27, $9b
	db $41, $0f
	dw @song0ref46
	db $41, $11
	dw @song0ref564
	db $41, $0f
	dw @song0ref46
@song0ref610:
	db $75, $84, $29, $77, $81, $75, $80, $3c, $79, $29, $9b, $4e, $fd, $81, $4e, $fc, $83, $4e, $ff, $81, $4e, $01, $81, $4e
	db $04, $83, $72, $4e, $03, $81, $4e, $00, $81
@song0ref643:
	db $75, $84, $2a, $77, $81, $75, $80, $3d, $79, $2a, $85, $72, $83, $75, $84, $29, $77, $81, $75, $80, $3c, $79, $29, $85
	db $72, $83
	db $41, $0c
	dw @song0ref643
	db $75, $84, $25, $48
@song0ref676:
	db $77, $81, $75, $80, $38, $79, $25, $85, $72, $83, $75, $84, $22, $77, $81, $75, $80, $35, $79, $22, $9b
	db $41, $0f
	dw @song0ref46
@song0ref700:
	db $75, $84, $22, $77, $81, $75, $80, $35, $79, $22, $97, $72, $83, $75, $84, $1b, $77, $81, $75, $80, $2e, $79, $1b, $97
	db $72, $83
@song0ref726:
	db $75, $84, $1e, $77, $81, $75, $80, $31, $79, $1e, $85, $72, $83, $75, $84, $20, $77, $81, $75, $80, $33, $79, $20, $85
	db $72, $83, $75, $84, $22, $77, $81, $75, $80, $35, $79, $22, $9b
	db $41, $0d
	dw @song0ref46
	db $41, $11
	dw @song0ref234
	db $41, $18
	dw @song0ref700
	db $75, $84, $1d, $77, $81, $75, $80, $30, $79, $1d, $9b
	db $41, $0d
	dw @song0ref46
	db $41, $0e
	dw @song0ref234
	db $48, $4e, $03, $81, $4e, $04, $81, $72, $4e, $00, $83
	db $41, $11
	dw @song0ref564
	db $41, $0f
	dw @song0ref46
	db $41, $11
	dw @song0ref564
	db $41, $0f
	dw @song0ref46
	db $41, $18
	dw @song0ref610
	db $41, $0c
	dw @song0ref643
	db $75, $84, $25
	db $41, $0a
	dw @song0ref676
	db $41, $0f
	dw @song0ref46
	db $41, $0c
	dw @song0ref700
	db $48
	db $41, $11
	dw @song0ref726
	db $41, $0f
	dw @song0ref46
	db $41, $0a
	dw @song0ref700
	db $9b
	db $41, $0f
	dw @song0ref362
	db $76
	db $41, $08
	dw @song0ref240
	db $41, $27
	dw @song0ref413
	db $4e, $fc, $83, $4e, $ff, $81, $4e, $00, $81, $4e, $03, $81, $4e, $04, $81
	db $41, $08
	dw @song0ref234
	db $00, $4e, $00, $ff, $97, $48, $ff, $ff, $ff, $ef, $75, $1b, $77, $81, $79, $82, $1b, $87, $72, $81, $48, $81
	db $41, $18
	dw @song0ref26
	db $41, $1d
	dw @song0ref15
	db $41, $15
	dw @song0ref101
	db $41, $0a
	dw @song0ref132
	db $41, $08
	dw @song0ref157
	db $41, $10
	dw @song0ref45
	db $41, $12
	dw @song0ref179
	db $48, $87, $72, $83, $75, $80, $22, $77, $81, $79, $82, $22
	db $41, $0e
	dw @song0ref45
	db $41, $14
	dw @song0ref234
	db $41, $11
	dw @song0ref187
	db $75, $80, $1d, $77, $81, $79, $82, $1d
	db $41, $0e
	dw @song0ref45
	db $41, $11
	dw @song0ref234
	db $41, $1d
	dw @song0ref15
	db $41, $0d
	dw @song0ref15
	db $99, $48, $83
	db $41, $0f
	dw @song0ref46
	db $41, $15
	dw @song0ref101
	db $41, $0a
	dw @song0ref132
	db $41, $08
	dw @song0ref157
	db $41, $10
	dw @song0ref45
	db $41, $17
	dw @song0ref179
	db $41, $10
	dw @song0ref45
	db $41, $08
	dw @song0ref179
	db $9d, $78, $4e, $fd, $81, $4e, $fc, $81, $42
	dw @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref992:
	db $72, $82, $0f, $a1
@song0ref996:
	db $76, $84, $1b, $79, $80, $1b, $1e, $81, $22, $81, $74, $1b, $71, $81, $1e, $81, $22, $81, $1b, $81, $1e, $81, $22, $81
	db $41, $12
	dw @song0ref996
@song0ref1023:
	db $72, $82, $11, $8f, $76, $84, $1d, $79, $80, $1d, $8d, $76, $81, $79, $81, $20, $81, $24, $81, $1d, $81, $20, $82, $20
	db $24, $81, $1d, $78, $81, $20, $81, $24, $81, $1d, $77, $81, $20, $81, $24, $81, $80, $1d, $81, $76, $20, $81, $24, $81
	db $1d, $81, $72, $20, $81, $24, $71, $81, $72, $82, $12, $a1
@song0ref1083:
	db $76, $84, $1e, $79, $80, $1e, $22, $81, $25, $81, $74, $1e, $71, $81, $22, $81, $25, $81, $1e, $81, $22, $81, $25, $81
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $41, $14
	dw @song0ref992
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $41, $14
	dw @song0ref992
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
@song0ref1143:
	db $72, $82, $17
@song0ref1146:
	db $a1
@song0ref1147:
	db $76, $84, $1b, $79, $80, $1b, $1e, $81, $23, $81, $74, $1b, $71, $81, $1e, $81, $23, $81, $1b, $81, $1e, $81, $23, $81
	db $41, $12
	dw @song0ref1147
@song0ref1174:
	db $72, $82, $12, $8f, $76, $84, $19, $79, $80, $19, $8d, $76, $81, $79, $81, $1e, $81, $22, $81, $19, $81, $1e, $82, $1e
	db $22, $81, $19, $78, $81, $1e, $81, $22, $81, $19, $77, $81, $1e, $81, $22, $81, $80, $19, $81, $76, $1e, $81, $22, $81
	db $19, $81, $72, $1e, $81, $22, $71, $81, $72, $82, $17, $95, $8b
	db $41, $12
	dw @song0ref1147
	db $41, $12
	dw @song0ref1147
@song0ref1241:
	db $72, $82, $16, $8f, $76, $84, $1a, $79, $80, $1a, $8d, $76, $81, $79, $81, $1d, $81, $22, $81, $1a, $81, $1d, $82, $1d
	db $22, $81, $1a, $78, $81, $1d, $81, $22, $81, $1a, $77, $81, $1d, $81, $22, $81, $80, $1a, $81, $76, $1d, $81, $22, $81
	db $1a, $81, $72, $1d, $81, $22, $71, $81
	db $41, $14
	dw @song0ref992
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $41, $14
	dw @song0ref1143
	db $41, $12
	dw @song0ref1147
	db $41, $29
	dw @song0ref1241
	db $41, $14
	dw @song0ref992
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $41, $14
	dw @song0ref992
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $41, $14
	dw @song0ref992
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $41, $14
	dw @song0ref1143
	db $41, $12
	dw @song0ref1147
	db $41, $2a
	dw @song0ref1174
	db $41, $13
	dw @song0ref1146
	db $41, $12
	dw @song0ref1147
	db $41, $29
	dw @song0ref1241
	db $41, $14
	dw @song0ref992
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $41, $14
	dw @song0ref1143
	db $41, $12
	dw @song0ref1147
	db $41, $29
	dw @song0ref1241
	db $41, $14
	dw @song0ref992
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $41, $14
	dw @song0ref992
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $72, $82, $0f, $8d, $93
	db $41, $12
	dw @song0ref996
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $41, $14
	dw @song0ref1143
	db $41, $12
	dw @song0ref1147
	db $41, $2a
	dw @song0ref1174
	db $41, $13
	dw @song0ref1146
	db $41, $12
	dw @song0ref1147
	db $41, $29
	dw @song0ref1241
	db $41, $14
	dw @song0ref992
	db $41, $12
	dw @song0ref996
	db $41, $3d
	dw @song0ref1023
	db $41, $12
	dw @song0ref1083
	db $41, $29
	dw @song0ref1023
	db $41, $14
	dw @song0ref1143
	db $41, $12
	dw @song0ref1147
	db $41, $29
	dw @song0ref1241
	db $72, $82, $0f, $a1, $76, $84, $1b, $79, $80, $1b, $42
	dw @song0ch1loop
@song0ch2:
@song0ch2loop:
	db $84
@song0ref1515:
	db $1b, $a3
@song0ref1517:
	db $30, $1b, $9f, $30, $1b
@song0ref1522:
	db $9f
@song0ref1523:
	db $1d, $8f, $18, $1d, $8d, $30, $1d, $8d
@song0ref1531:
	db $30, $1d, $8d
@song0ref1534:
	db $30, $1d, $9d, $1e, $a3, $30, $1e, $9f, $30, $1e
	db $41, $0f
	dw @song0ref1522
	db $1b, $a3, $30, $1b, $9f, $30, $1b, $81, $9d
	db $41, $15
	dw @song0ref1523
	db $41, $0f
	dw @song0ref1522
	db $41, $0f
	dw @song0ref1515
	db $89, $83
	db $41, $0d
	dw @song0ref1531
	db $41, $0f
	dw @song0ref1522
@song0ref1573:
	db $23, $a3, $30, $23, $9f, $30, $23, $9f
@song0ref1581:
	db $1e, $8f, $18, $1e, $8d, $30, $1e, $8d, $30, $1e, $8d, $30, $1e, $9d, $23, $95, $8d
@song0ref1598:
	db $30, $23, $9f
@song0ref1601:
	db $30, $23, $9f
@song0ref1604:
	db $22, $8f, $18, $22, $8d, $30, $22, $8d, $30, $22, $8d, $30, $22, $9d
	db $41, $1d
	dw @song0ref1515
	db $99, $85
	db $41, $0e
	dw @song0ref1523
	db $41, $08
	dw @song0ref1573
	db $41, $0e
	dw @song0ref1604
	db $41, $1d
	dw @song0ref1515
	db $41, $0f
	dw @song0ref1522
	db $41, $1a
	dw @song0ref1515
	db $85, $99, $30, $1e
	db $41, $0f
	dw @song0ref1522
	db $41, $1d
	dw @song0ref1515
	db $41, $0f
	dw @song0ref1522
	db $41, $17
	dw @song0ref1573
	db $a3
	db $41, $13
	dw @song0ref1598
	db $95, $87
	db $41, $1d
	dw @song0ref1515
	db $41, $0f
	dw @song0ref1522
	db $23, $a3, $30, $23, $9d, $81
	db $41, $11
	dw @song0ref1601
	db $41, $1d
	dw @song0ref1515
	db $41, $08
	dw @song0ref1522
	db $81, $8b, $30, $1d, $8d, $30, $1d, $9d
	db $41, $1d
	dw @song0ref1515
	db $41, $0f
	dw @song0ref1522
	db $1b, $8d, $95
	db $41, $1b
	dw @song0ref1517
	db $41, $0f
	dw @song0ref1522
	db $23, $a3, $30, $23, $9f, $30, $23, $91, $8d
	db $41, $0f
	dw @song0ref1581
	db $a3
	db $41, $14
	dw @song0ref1598
	db $41, $12
	dw @song0ref1515
	db $87, $85
	db $41, $0a
	dw @song0ref1534
	db $41, $0f
	dw @song0ref1522
	db $41, $08
	dw @song0ref1573
	db $41, $0e
	dw @song0ref1604
	db $1b, $a3, $30, $42
	dw @song0ch2loop
@song0ch3:
@song0ch3loop:
	db $a3, $76, $84
@song0ref1750:
	db $1c, $71, $81, $00, $9d
@song0ref1755:
	db $76, $1c, $71, $81, $00, $af
@song0ref1761:
	db $76, $18, $71, $81, $00, $8b, $76, $1c, $71, $81, $00, $8b
@song0ref1773:
	db $76, $1c, $71, $81, $00, $8b, $76, $1c, $71, $81, $00, $c1, $76
	db $41, $18
	dw @song0ref1750
	db $76, $1c, $71, $81, $00, $9d, $76, $1c, $71, $81, $00, $81, $ad
	db $41, $10
	dw @song0ref1761
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $0f
	dw @song0ref1750
	db $89, $81
	db $41, $08
	dw @song0ref1773
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $17
	dw @song0ref1750
	db $b5, $8b, $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76, $1c, $71, $81, $00, $9d, $76, $1c, $71, $81, $00, $99, $95
	db $41, $10
	dw @song0ref1761
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76, $1c, $71, $81, $00, $85, $97
	db $41, $14
	dw @song0ref1755
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $17
	dw @song0ref1750
	db $95, $ab, $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $0f
	dw @song0ref1750
	db $81, $89
	db $41, $08
	dw @song0ref1773
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $17
	dw @song0ref1750
	db $ad, $93, $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76, $1c, $71, $81, $00, $9d, $76, $1c, $71, $81, $00, $91, $9d
	db $41, $10
	dw @song0ref1761
	db $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $13
	dw @song0ref1750
	db $87, $83, $76, $1c, $71, $81, $00, $c1, $76
	db $41, $18
	dw @song0ref1750
	db $76
	db $41, $18
	dw @song0ref1750
	db $76, $1c, $71, $81, $42
	dw @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1987:
	db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	db $41, $08
	dw @song0ref1987
	db $41, $08
	dw @song0ref1987
	db $41, $08
	dw @song0ref1987
	db $41, $08
	dw @song0ref1987
	db $41, $08
	dw @song0ref1987
	db $41, $08
	dw @song0ref1987
	db $42
	dw @song0ch4loop
